-- GENERATED by tools/map.luau from assets/environment/source/KitOutposts.rbxm -- do not edit.
--
-- Move objectives, spawns and the boundary in Studio, save the source, then run
--     bash tools/save_map.sh KitOutposts
-- Sky, lighting and terrain: edit assets/environment/source/KitOutposts.presentation.lua instead.
-- See assets/environment/source/README.md.
-- stylua: ignore start
return {
    Name = "KitOutposts",
    Revision = "src-15a4e708f0",
    Draft = true,
    RequiresBake = true,
    Authored = {
        Format = 1,
        Presentation = "assets/environment/source/KitOutposts.presentation.lua",
        Source = "assets/environment/source/KitOutposts.rbxm",
    },
    Size = 490,
    WallHeight = 12,
    Seed = 0,
    Finale = { EligibleIds = { "A", "B", "C" } },
    Objectives = {
        {
            Id = "A",
            Name = "West Ice",
            Phases = { 1, 2, 3 },
            halfHeight = 7,
            pos = { -150, 0, 0 },
            radius = 18,
        },
        {
            Id = "B",
            Name = "East Ice",
            Phases = { 1, 2, 3 },
            halfHeight = 7,
            pos = { 150, 0, 0 },
            radius = 18,
        },
        {
            Id = "C",
            Name = "Helipad",
            Phases = { 1, 2, 3 },
            halfHeight = 7,
            pos = { 0, 0.2, 0 },
            radius = 18,
        },
    },
    Spawns = {
        Blue = {
            { -20, 0, -150 },
            { -12, 0, -150 },
            { -4, 0, -150 },
            { 4, 0, -150 },
            { 12, 0, -150 },
            { 20, 0, -150 },
        },
        Red = {
            { -20, 0, 150 },
            { -12, 0, 150 },
            { -4, 0, 150 },
            { 4, 0, 150 },
            { 12, 0, 150 },
            { 20, 0, 150 },
        },
    },
    Bounds = { max = { 245, 85, 185 }, min = { -245, -12, -185 } },
    RecoveryY = -12,
    SafetyAlwaysOn = true,
    SafePoints = {
        { name = "Blue spawn", pos = { -4, 1, -150 } },
        { name = "Red spawn", pos = { -4, 1, 150 } },
        { name = "Objective A", pos = { -150, 1, 0 } },
        { name = "Objective B", pos = { 150, 1, 0 } },
        { name = "Objective C", pos = { 0, 1.2, 0 } },
    },
    Barrier = {
        { pos = { 0, 6, -186.5 }, size = { 490, 12, 1.5 } },
        { pos = { 0, 6, 186.5 }, size = { 490, 12, 1.5 } },
        { pos = { -246.5, 6, 0 }, size = { 1.5, 12, 370 } },
        { pos = { 246.5, 6, 0 }, size = { 1.5, 12, 370 } },
    },
    InvalidRegions = {},
    SafeRegions = {},
    Vista = { look = { 0, 8, 0 }, pos = { -225, 80, -190 }, seconds = 3 },
    Terrain = { GroundColor = Color3.fromRGB(226, 233, 240), GroundMaterial = Enum.Material.Snow },
    Palette = {
        Cover = Color3.fromRGB(122, 130, 140),
        Floor = Color3.fromRGB(180, 184, 190),
        Wall = Color3.fromRGB(102, 110, 122),
    },
    Environment = {
        Ambient = Color3.fromRGB(160, 160, 160),
        Atmosphere = { Color = Color3.fromRGB(255, 255, 255), Density = 0, Glare = 0, Haze = 0 },
        Bloom = 0,
        Brightness = 2,
        ClockTime = 12,
        Contrast = 0,
        FogColor = Color3.fromRGB(190, 195, 205),
        FogEnd = 3000,
        FogStart = 900,
        OutdoorAmbient = Color3.fromRGB(170, 170, 170),
        Saturation = 0,
        Sky = {
            Bk = "rbxassetid://2029210131",
            CelestialBodiesShown = true,
            Dn = "rbxassetid://2029210773",
            Ft = "rbxassetid://2029211409",
            Lf = "rbxassetid://2029212393",
            Rt = "rbxassetid://2029212849",
            Up = "rbxassetid://2029213271",
        },
        SunRays = 0,
        Tint = Color3.fromRGB(255, 255, 255),
    },
    Center = {},
    Mirrored = {},
    Decor = {},
}
-- stylua: ignore end
