-- Snow Fortress: gameplay data. The geometry is NOT here.
--
-- Every part of this map lives in assets/environment/baked/SnowFortress.rbxm, arranged
-- in Studio and saved as a model. MapService clones it; nothing below places a block.
-- Code was the right tool while the layout was being generated -- loops, mirrors,
-- parametric structure -- and the wrong one once it was being detailed, where every
-- change is a visual judgement and the round trip ran through a commit and a restart.
--
-- What stays here is what is not geometry: objectives, spawns, routes, bounds, safety
-- points, palette and sky. Services read these, they have to be diffable, and they are
-- small. The gates read the .rbxm for geometry and this file for everything else.
--
-- To change the map: open Studio, drag ServerStorage.BakedMaps.SnowFortress into
-- Workspace, edit, then right-click -> Save to File over the .rbxm. See
-- assets/environment/baked/README.md.
-- North = -Z, Blue = west (-X), Red = east (+X).
local map = {
    Name = "SnowFortress",
    Revision = "enclosed-fortress-v3",
    Size = 500,
    WallHeight = 12,
    Seed = 1129,
    Finale = { EligibleIds = { "gate", "yard", "keep" } },
    -- Generated by the builder that used to live in this file, written out literally
    -- when it was deleted. None of it is geometry -- services read all of it -- but it
    -- was computed rather than typed, so removing the loops silently emptied it. The
    -- fortress gate caught that: "each team needs six exterior spawns".
    Spawns = {
        Blue = { { -210, 0, -20 }, { -210, 0, -12 }, { -210, 0, -4 }, { -210, 0, 4 }, { -210, 0, 12 }, { -210, 0, 20 } },
        Red = { { 210, 0, -20 }, { 210, 0, -12 }, { 210, 0, -4 }, { 210, 0, 4 }, { 210, 0, 12 }, { 210, 0, 20 } },
    },
    Objectives = {
        {
            Id = "gate",
            Name = "A — North Field",
            pos = { 0, 0.2, -128 },
            radius = 18,
            halfHeight = 7,
            Phases = { 1, 2, 3 },
        },
        {
            Id = "yard",
            Name = "B — South Field",
            pos = { 0, 0.2, 128 },
            radius = 18,
            halfHeight = 7,
            Phases = { 1, 2, 3 },
        },
        {
            Id = "keep",
            Name = "C — Fortress Upper Floor",
            pos = { 0, 18.2, 0 },
            radius = 18,
            halfHeight = 7,
            Phases = { 1, 2, 3 },
        },
    },
    Vista = { pos = { -225, 80, -190 }, look = { 0, 8, 0 }, seconds = 3 },
    SafetyAlwaysOn = true,
    RecoveryY = -8,
    Bounds = { min = { -245, -12, -185 }, max = { 245, 85, 185 } },
    InvalidRegions = {},
    SafeRegions = {},
    SafePoints = {
        { name = "Blue exterior", pos = { -200, 1, 0 } },
        { name = "Red exterior", pos = { 200, 1, 0 } },
        { name = "North field", pos = { 0, 1, -128 } },
        { name = "South field", pos = { 0, 1, 128 } },
        { name = "Fortress upper centre", pos = { 0, 19, 0 } },
        { name = "Upper landing southwest", pos = { -60, 19, 46 } },
        { name = "Upper landing northeast", pos = { 60, 19, -46 } },
    },
    Barrier = {
        { pos = { 0, 6, -186.5 }, size = { 490, 12, 1.5 } },
        { pos = { 0, 6, 186.5 }, size = { 490, 12, 1.5 } },
        { pos = { -246.5, 6, 0 }, size = { 1.5, 12, 370 } },
        { pos = { 246.5, 6, 0 }, size = { 1.5, 12, 370 } },
    },
    -- The horizon is a skybox (tools/blender/make_sky_range.py), not geometry:
    -- FillBall domes read as bald mounds and a terrain scan smears when seen from
    -- the side. Terrain here is only the snowfield the arena sits on.
    Terrain = {
        GroundMaterial = Enum.Material.Snow,
        GroundColor = Color3.fromRGB(226, 233, 240),
    },
    Palette = {
        Floor = Color3.fromRGB(180, 184, 190),
        Wall = Color3.fromRGB(102, 110, 122),
        Cover = Color3.fromRGB(122, 130, 140),
        Upper = Color3.fromRGB(154, 165, 180),
        Ramp = Color3.fromRGB(200, 204, 212),
        -- The roof is its own surface, not more of the interior. It was `Upper`, the
        -- same near-white as the floor below, which left a white wreck on a white deck
        -- under a white sky with nothing to separate them. Darker and slightly bluer
        -- so it reads as built structure against snow, and so red and blue players on
        -- it have something to contrast against.
        Deck = Color3.fromRGB(116, 124, 136),
        -- Helipad. The deck is dark enough to anchor the wreck; the markings are the
        -- only warm value on the map, which is what makes them read as paint.
        PadDeck = Color3.fromRGB(74, 80, 88),
        PadMark = Color3.fromRGB(214, 196, 110),
        -- Burn under the wreck, over the pad. The point is contrast, not colour.
        Scorch = Color3.fromRGB(58, 56, 58),
    },
    Environment = {
        -- "Snowy Sky Box" by @DonTheBears, Creator Store asset 2029216718, found under
        -- Visual Effects / Sky and Atmosphere -- the category that holds real Sky
        -- objects rather than skyboxes faked out of parts. Six distinct face images,
        -- which is what a continuous range needs; a skybox repeating one image on all
        -- four sides cannot be one. Two generated ranges were tried first and neither
        -- was good enough; see docs/design/ASSET_INTAKE_AND_LESSONS.md.
        Sky = {
            Ft = "rbxassetid://2029211409",
            Bk = "rbxassetid://2029210131",
            Lf = "rbxassetid://2029212393",
            Rt = "rbxassetid://2029212849",
            Up = "rbxassetid://2029213271",
            Dn = "rbxassetid://2029210773",
            CelestialBodiesShown = true,
        },
        ClockTime = 12,
        Brightness = 2,
        Ambient = Color3.fromRGB(160, 160, 160),
        OutdoorAmbient = Color3.fromRGB(170, 170, 170),
        -- Nothing sits beyond about 1080 studs now, so this only adds depth haze
        -- to the horizon. The arena is under 620 studs corner to corner, so no
        -- fog falls inside it.
        FogStart = 900,
        FogEnd = 3000,
        FogColor = Color3.fromRGB(190, 195, 205),
        Atmosphere = { Density = 0, Haze = 0, Glare = 0, Color = Color3.fromRGB(255, 255, 255) },
        SunRays = 0,
        Bloom = 0,
        Saturation = 0,
        Contrast = 0,
        Tint = Color3.fromRGB(255, 255, 255),
    },
    Center = {},
    Mirrored = {},
    -- Scenery. Built into its own folder and never part of the gameplay model, so a
    -- change here needs no review and cannot move a wall by accident.
    Decor = {},
    Symmetry = { SniperOutposts = "rotational" },
    GroundRoutes = {
        {
            DistrictId = "gate",
            From = { -210, 1, -24 },
            Id = "blue-north",
            Kind = "covered",
            Side = "Blue",
            To = { 0, 1, -128 },
            Waypoints = { { -210, 1, -24 }, { -180, 1, -48 }, { -95, 1, -95 }, { 0, 1, -128 } },
        },
        {
            DistrictId = "yard",
            From = { -210, 1, 24 },
            Id = "blue-south",
            Kind = "covered",
            Side = "Blue",
            To = { 0, 1, 128 },
            Waypoints = { { -210, 1, 24 }, { -180, 1, 48 }, { -95, 1, 95 }, { 0, 1, 128 } },
        },
        {
            DistrictId = "keep",
            From = { -210, 1, 0 },
            Id = "blue-centre",
            Kind = "direct",
            Side = "Blue",
            To = { 0, 19, 0 },
            Waypoints = {
                { -210, 1, 0 },
                { -190, 1, 38 },
                { -160, 1, 38 },
                { -95, 1, 0 },
                { -70, 5, 0 },
                { 0, 5, 0 },
                { -40, 5, 0 },
                { -40, 19, -40 },
                { 0, 19, -40 },
                { 0, 19, 0 },
            },
        },
        {
            DistrictId = "gate",
            From = { 210, 1, -24 },
            Id = "red-north",
            Kind = "covered",
            Side = "Red",
            To = { 0, 1, -128 },
            Waypoints = { { 210, 1, -24 }, { 180, 1, -48 }, { 95, 1, -95 }, { 0, 1, -128 } },
        },
        {
            DistrictId = "yard",
            From = { 210, 1, 24 },
            Id = "red-south",
            Kind = "covered",
            Side = "Red",
            To = { 0, 1, 128 },
            Waypoints = { { 210, 1, 24 }, { 180, 1, 48 }, { 95, 1, 95 }, { 0, 1, 128 } },
        },
        {
            DistrictId = "keep",
            From = { 210, 1, 0 },
            Id = "red-centre",
            Kind = "direct",
            Side = "Red",
            To = { 0, 19, 0 },
            Waypoints = {
                { 210, 1, 0 },
                { 190, 1, 38 },
                { 160, 1, 38 },
                { 95, 1, 0 },
                { 70, 5, 0 },
                { 0, 5, 0 },
                { 40, 5, 0 },
                { 40, 19, 40 },
                { 0, 19, 40 },
                { 0, 19, 0 },
            },
        },
        {
            DistrictId = "keep",
            From = { 0, 1, -128 },
            Id = "north-ramp",
            Kind = "direct",
            Side = "Both",
            To = { 0, 19, 0 },
            Waypoints = {
                { 0, 1, -128 },
                { 0, 1, -72 },
                { 0, 5, -54 },
                { 0, 5, 0 },
                { 40, 5, 0 },
                { 40, 19, 40 },
                { 0, 19, 40 },
                { 0, 19, 0 },
            },
        },
        {
            DistrictId = "keep",
            From = { 0, 1, 128 },
            Id = "south-ramp",
            Kind = "direct",
            Side = "Both",
            To = { 0, 19, 0 },
            Waypoints = {
                { 0, 1, 128 },
                { 0, 1, 72 },
                { 0, 5, 54 },
                { 0, 5, 0 },
                { 40, 5, 0 },
                { 40, 19, 40 },
                { 0, 19, 40 },
                { 0, 19, 0 },
            },
        },
    },
    SniperOutposts = {
        {
            Id = "northwest",
            Name = "Northwest Outpost",
            pos = { -145, 19, -126 },
            radius = 12,
            GroundRouteId = "blue-north",
        },
        {
            Id = "southeast",
            Name = "Southeast Outpost",
            pos = { 145, 19, 126 },
            radius = 12,
            GroundRouteId = "red-south",
        },
    },
    LaunchPads = {
        {
            GroundAlternative = "blue-centre",
            Id = "Blue-north-launch",
            pos = { -125, 0.3, -30 },
            size = 8,
            target = { -84, 2, -5 },
            vy = 62,
        },
        {
            GroundAlternative = "blue-centre",
            Id = "Blue-south-launch",
            pos = { -125, 0.3, 30 },
            size = 8,
            target = { -84, 2, 5 },
            vy = 62,
        },
        {
            GroundAlternative = "red-centre",
            Id = "Red-north-launch",
            pos = { 125, 0.3, -30 },
            size = 8,
            target = { 84, 2, -5 },
            vy = 62,
        },
        {
            GroundAlternative = "red-centre",
            Id = "Red-south-launch",
            pos = { 125, 0.3, 30 },
            size = 8,
            target = { 84, 2, 5 },
            vy = 62,
        },
    },
    ZipLines = {
        {
            Id = "southwest-upper",
            From = { -150, 4, 130 },
            To = { -55, 38, 50 },
            GroundAlternative = "blue-centre",
            Purpose = "Southwest exterior to roof hatch",
        },
        {
            Id = "northeast-upper",
            From = { 150, 4, -130 },
            To = { 55, 38, -50 },
            GroundAlternative = "red-centre",
            Purpose = "Northeast exterior to roof hatch",
        },
    },
    -- No grapple routes in the new authoritative sketch.
    GrappleAnchors = {},
    ReviewViews = {
        { Name = "01-overhead", Eye = { 0, 470, 0 }, Look = { 0, 0, 0 }, Up = { 0, 0, -1 } },
        { Name = "02-blue-spawn", Eye = { -210, 6, 0 }, Look = { 0, 10, 0 } },
        { Name = "03-red-spawn", Eye = { 210, 6, 0 }, Look = { 0, 10, 0 } },
        { Name = "04-capture-a", Eye = { 0, 6, -143 }, Look = { 0, 8, -35 } },
        { Name = "05-capture-b", Eye = { 0, 6, 143 }, Look = { 0, 8, 35 } },
        { Name = "06-capture-c", Eye = { -16, 24, 16 }, Look = { 18, 22, -18 } },
        { Name = "07-northwest-outpost", Eye = { -145, 24, -126 }, Look = { 0, 20, 0 } },
        { Name = "08-southeast-outpost", Eye = { 145, 24, 126 }, Look = { 0, 20, 0 } },
        { Name = "09-southwest-zip", Eye = { -162, 7, 142 }, Look = { -60, 20, 46 } },
        { Name = "10-northeast-zip", Eye = { 162, 7, -142 }, Look = { 60, 20, -46 } },
        { Name = "11-second-story", Eye = { -61, 24, 43 }, Look = { 60, 19, -43 } },
        { Name = "12-ground-entrances", Eye = { -115, 60, -105 }, Look = { 0, 3, 0 } },
    },
    -- No geometry in this file, so a missing bake is a hard failure rather than an
    -- empty world. MapService refuses to build instead of shipping a skybox.
    RoofHatches = { { -55, 33, 40 }, { 55, 33, -40 } },
    RequiresBake = true,
}

return map
