"""Generate an explicit, local Studio review assembler from the asset manifest.
This does not upload assets or alter the live map. Run with normal Python.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "assets/environment/snow-fortress/entrance-kit-v1"
manifest = json.loads((OUT / "manifest.json").read_text())
assembly = json.loads((OUT / "review-assembly.json").read_text())
header = """-- Generated by tools/blender/prepare_fortress_import.py.
-- EDIT MODE ONLY. Import the seven GLBs into Workspace.SnowFortressKitImports,
-- each as a Model named exactly as its file stem. Keep import scale unit Stud.
-- This creates an isolated review model, not a runtime map installation.
local HttpService = game:GetService("HttpService")
local RunService = game:GetService("RunService")
assert(not RunService:IsRunning(), "Run this in Studio edit mode")
local imports = assert(workspace:FindFirstChild("SnowFortressKitImports"), "Missing imported kit folder")
assert(not workspace:FindFirstChild("SnowFortressBlenderReview"), "A review model already exists; move or remove it first")
local origin = Vector3.new(0, 1000, 0)
"""
script = header + "local manifest = HttpService:JSONDecode([==[" + json.dumps(manifest) + "]==])\n"
script += "local assembly = HttpService:JSONDecode([==[" + json.dumps(assembly) + "]==])\n"
script += """
-- GLB Y-up basis: Blender (x,y,z) -> Roblox (x,z,-y).
local function point(p) return Vector3.new(p[1], p[3], -p[2]) end
local function dimensions(p) return Vector3.new(p[1], p[3], p[2]) end
local function aabb(model)
    local lo, hi = Vector3.new(math.huge, math.huge, math.huge), Vector3.new(-math.huge, -math.huge, -math.huge)
    local count = 0
    for _, part in model:GetDescendants() do
        if part:IsA("BasePart") then
            count += 1
            for _, x in {-1, 1} do for _, y in {-1, 1} do for _, z in {-1, 1} do
                local p = part.CFrame:PointToWorldSpace(part.Size * Vector3.new(x,y,z) / 2)
                lo = Vector3.new(math.min(lo.X,p.X),math.min(lo.Y,p.Y),math.min(lo.Z,p.Z))
                hi = Vector3.new(math.max(hi.X,p.X),math.max(hi.Y,p.Y),math.max(hi.Z,p.Z))
            end end end
        end
    end
    assert(count > 0, model.Name .. " contains no geometry")
    return (lo + hi) / 2, hi - lo
end
-- Validate every template before creating anything. Never silently rescale a bad import.
for name, spec in manifest.modules do
    local model = assert(imports:FindFirstChild(name), "Missing module " .. name)
    assert(model:IsA("Model"), name .. " must be imported as a Model")
    local _, size = aabb(model)
    local expected = dimensions({spec.boundsMax[1]-spec.boundsMin[1], spec.boundsMax[2]-spec.boundsMin[2], spec.boundsMax[3]-spec.boundsMin[3]})
    assert((size-expected).Magnitude < 0.08, name .. " has wrong scale/orientation; use GLB, Y up, Scale Unit Stud")
end
local review = Instance.new("Model")
review.Name = "SnowFortressBlenderReview"
review:SetAttribute("Source", "entrance-kit-v1")
review:SetAttribute("Status", "Imported review slice; not installed in Convergence")
local ok, err = pcall(function()
    for index, placement in assembly.placements do
        local spec = manifest.modules[placement.module]
        local group = Instance.new("Model")
        group.Name = string.format("%02d_%s", index, placement.module)
        group.Parent = review
        local visual = imports[placement.module]:Clone()
        visual.Name = "Visual"
        visual.Parent = group
        local currentCenter = aabb(visual)
        local localCenter = point({(spec.boundsMin[1]+spec.boundsMax[1])/2,
            (spec.boundsMin[2]+spec.boundsMax[2])/2, (spec.boundsMin[3]+spec.boundsMax[3])/2})
        local base = CFrame.new(origin + point(placement.position)) * CFrame.Angles(0, placement.rotationZ or 0, 0)
        visual:PivotTo(CFrame.new(localCenter-currentCenter) * visual:GetPivot())
        visual:PivotTo(base * visual:GetPivot())
        for _, part in visual:GetDescendants() do
            if part:IsA("BasePart") then
                part.Anchored, part.CanCollide, part.CanTouch, part.CanQuery = true, false, false, false
            end
        end
        for _, box in spec.collisionBoxes do
            local part = Instance.new("Part")
            part.Name = "Collision_" .. box.name
            part.Size = dimensions(box.size)
            part.CFrame = base * CFrame.new(point(box.center))
            part.Anchored, part.CanCollide, part.CanQuery, part.CanTouch = true, true, true, false
            part.Transparency, part.CastShadow = 1, false
            part.Parent = group
        end
    end
end)
if not ok then review:Destroy(); error(err) end
review.Parent = workspace
game:GetService("Selection"):Set({review})
print("Review kit assembled at Y=1000. Foundation/ramp, lighting and mannequin are Blender staging only. No live map changed.")
"""
(OUT / "assemble_review.luau").write_text(script, encoding="utf-8")
print("Generated", OUT / "assemble_review.luau")

slice_script = '''-- Select the imported SnowFortress_ReviewSlice Model in a NEW test place.
-- Paste this file into Studio's Command Bar in EDIT mode, then press Play.
local HttpService = game:GetService("HttpService")
assert(not game:GetService("RunService"):IsRunning(), "Stop play before setup")
local selected = game:GetService("Selection"):Get()
assert(#selected == 1 and selected[1]:IsA("Model"), "Select the imported review Model")
local model = selected[1]
assert(not model:FindFirstChild("KitTestSetup"), "This model is already configured")
local ground
for _, part in model:GetDescendants() do
    if part:IsA("BasePart") and math.abs(part.Size.X-110) < 0.1 and math.abs(part.Size.Z-110) < 0.1 and part.Size.Y < 1 then
        ground = part
    end
end
assert(ground, "Expected 110-stud test floor: import GLB with Scale Unit Stud, Y up")
local origin = ground.Position + Vector3.new(0, 4.3, 0)
'''
slice_script += "local manifest = HttpService:JSONDecode([==[" + json.dumps(manifest) + "]==])\n"
slice_script += "local assembly = HttpService:JSONDecode([==[" + json.dumps(assembly) + "]==])\n"
slice_script += '''
local function point(p) return Vector3.new(p[1], p[3], -p[2]) end
local setup = Instance.new("Folder")
setup.Name = "KitTestSetup"
local function solid(name, size, cf)
    local p = Instance.new("Part")
    p.Name, p.Size, p.CFrame = name, size, cf
    p.Anchored, p.CanCollide, p.CanQuery, p.CanTouch = true, true, true, false
    p.Transparency, p.CastShadow = 1, false
    p.Parent = setup
    return p
end
for _, placement in assembly.placements do
    local base = CFrame.new(origin + point(placement.position)) * CFrame.Angles(0, placement.rotationZ or 0, 0)
    for _, box in manifest.modules[placement.module].collisionBoxes do
        solid(placement.module .. "_" .. box.name, Vector3.new(box.size[1],box.size[3],box.size[2]), base * CFrame.new(point(box.center)))
    end
end
solid("Test ground", Vector3.new(110,0.6,110), CFrame.new(origin + Vector3.new(0,-4.3,0)))
solid("Foundation", Vector3.new(58,3.98,32), CFrame.new(origin + Vector3.new(0,-2.01,-12)))
local angle = math.rad(20)
local run = 4/math.tan(angle)
solid("Entrance ramp", Vector3.new(24,0.5,4/math.sin(angle)),
    CFrame.new(origin + Vector3.new(0,-2-0.25*math.cos(angle),run/2)) * CFrame.Angles(angle,0,0))
for _, depth in {2,10,22} do
    local anchor = solid("Light anchor",Vector3.new(0.1,0.1,0.1),CFrame.new(origin+Vector3.new(0,12.5,-depth)))
    anchor.CanCollide, anchor.CanQuery = false, false
    local light = Instance.new("PointLight")
    light.Color, light.Brightness, light.Range = Color3.fromRGB(255,214,155), 1.5, 24
    light.Shadows = true
    light.Parent = anchor
end
-- Detailed visual meshes do not determine collision: the authored boxes do.
for _, part in model:GetDescendants() do
    if part:IsA("BasePart") then
        part.Anchored, part.CanCollide, part.CanQuery, part.CanTouch = true, false, false, false
    end
end
setup.Parent = model
local spawn = Instance.new("SpawnLocation")
spawn.Name = "KitTestSpawn"
spawn.Size = Vector3.new(6,1,6)
spawn.CFrame = CFrame.new(origin + Vector3.new(0,-3.5,38))
spawn.Anchored, spawn.Neutral, spawn.Duration = true, true, 0
spawn.Parent = setup
model:SetAttribute("KitReviewReady", true)
workspace.CurrentCamera.CFrame = CFrame.lookAt(origin + Vector3.new(-25,2,55),origin + Vector3.new(0,8,-3))
print("Kit ready for an isolated test. Remove the baseplate's default SpawnLocation so Play uses KitTestSpawn. This is not installed in Convergence.")
'''
(OUT / "setup_imported_slice.luau").write_text(slice_script, encoding="utf-8")
print("Generated", OUT / "setup_imported_slice.luau")
